// FO_STOCKS — NSE F&O (Derivatives on Individual Securities) universe
// 208 liquid, options-tradable stocks. Sourced from NSE's fo_mktlots.csv.
// This is the scan universe for the Weekly Equity Scanner — broader than the
// NIFTY 50 and all symbols are F&O-tradable with weekly expiries.

export interface UniverseStock {
  symbol: string;
  name: string;
  sector: string;
}

export const FO_STOCKS: UniverseStock[] = [
  { symbol: "360ONE", name: "360 ONE WAM LIMITED", sector: "Finance" },
  { symbol: "ABB", name: "ABB INDIA LIMITED", sector: "Capital Goods" },
  { symbol: "ABCAPITAL", name: "ADITYA BIRLA CAPITAL LTD.", sector: "NBFC" },
  { symbol: "ADANIENSOL", name: "ADANI ENERGY SOLUTION LTD", sector: "Energy" },
  { symbol: "ADANIENT", name: "ADANI ENTERPRISES LIMITED", sector: "Conglomerate" },
  { symbol: "ADANIGREEN", name: "ADANI GREEN ENERGY LTD", sector: "Energy" },
  { symbol: "ADANIPORTS", name: "ADANI PORT & SEZ LTD", sector: "Infrastructure" },
  { symbol: "ADANIPOWER", name: "ADANI POWER LTD", sector: "Power" },
  { symbol: "ALKEM", name: "ALKEM LABORATORIES LTD.", sector: "Pharma" },
  { symbol: "AMBER", name: "AMBER ENTERPRISES (I) LTD", sector: "Consumer" },
  { symbol: "AMBUJACEM", name: "AMBUJA CEMENTS LTD", sector: "Cement" },
  { symbol: "ANGELONE", name: "ANGEL ONE LIMITED", sector: "Finance" },
  { symbol: "APLAPOLLO", name: "APL APOLLO TUBES LTD", sector: "Metal" },
  { symbol: "APOLLOHOSP", name: "APOLLO HOSPITALS ENTER. L", sector: "Healthcare" },
  { symbol: "ASHOKLEY", name: "ASHOK LEYLAND LTD", sector: "Auto" },
  { symbol: "ASIANPAINT", name: "ASIAN PAINTS LIMITED", sector: "Consumer" },
  { symbol: "ASTRAL", name: "ASTRAL LIMITED", sector: "Capital Goods" },
  { symbol: "AUBANK", name: "AU SMALL FINANCE BANK LTD", sector: "Banking" },
  { symbol: "AUROPHARMA", name: "AUROBINDO PHARMA LTD", sector: "Pharma" },
  { symbol: "AXISBANK", name: "AXIS BANK LIMITED", sector: "Banking" },
  { symbol: "BAJAJ-AUTO", name: "BAJAJ AUTO LIMITED", sector: "Auto" },
  { symbol: "BAJAJFINSV", name: "BAJAJ FINSERV LTD.", sector: "NBFC" },
  { symbol: "BAJAJHLDNG", name: "BAJAJ HOLDINGS & INVS LTD", sector: "NBFC" },
  { symbol: "BAJFINANCE", name: "BAJAJ FINANCE LIMITED", sector: "NBFC" },
  { symbol: "BANDHANBNK", name: "BANDHAN BANK LIMITED", sector: "Banking" },
  { symbol: "BANKBARODA", name: "BANK OF BARODA", sector: "Banking" },
  { symbol: "BANKINDIA", name: "BANK OF INDIA", sector: "Banking" },
  { symbol: "BDL", name: "BHARAT DYNAMICS LIMITED", sector: "Defence" },
  { symbol: "BEL", name: "BHARAT ELECTRONICS LTD", sector: "Defence" },
  { symbol: "BHARATFORG", name: "BHARAT FORGE LTD", sector: "Auto" },
  { symbol: "BHARTIARTL", name: "BHARTI AIRTEL LIMITED", sector: "Telecom" },
  { symbol: "BHEL", name: "BHEL", sector: "Capital Goods" },
  { symbol: "BIOCON", name: "BIOCON LIMITED.", sector: "Pharma" },
  { symbol: "BLUESTARCO", name: "BLUE STAR LIMITED", sector: "Capital Goods" },
  { symbol: "BOSCHLTD", name: "BOSCH LIMITED", sector: "Auto" },
  { symbol: "BPCL", name: "BHARAT PETROLEUM CORP  LT", sector: "Energy" },
  { symbol: "BRITANNIA", name: "BRITANNIA INDUSTRIES LTD", sector: "FMCG" },
  { symbol: "BSE", name: "BSE LIMITED", sector: "Finance" },
  { symbol: "CAMS", name: "COMPUTER AGE MNGT SER LTD", sector: "Finance" },
  { symbol: "CANBK", name: "CANARA BANK", sector: "Banking" },
  { symbol: "CDSL", name: "CENTRAL DEPO SER (I) LTD", sector: "Finance" },
  { symbol: "CGPOWER", name: "CG POWER AND IND SOL LTD", sector: "Capital Goods" },
  { symbol: "CHOLAFIN", name: "CHOLAMANDALAM IN & FIN CO", sector: "NBFC" },
  { symbol: "CIPLA", name: "CIPLA LTD", sector: "Pharma" },
  { symbol: "COALINDIA", name: "COAL INDIA LTD", sector: "Mining" },
  { symbol: "COCHINSHIP", name: "COCHIN SHIPYARD LIMITED", sector: "Defence" },
  { symbol: "COFORGE", name: "COFORGE LIMITED", sector: "IT" },
  { symbol: "COLPAL", name: "COLGATE PALMOLIVE LTD.", sector: "FMCG" },
  { symbol: "CONCOR", name: "CONTAINER CORP OF IND LTD", sector: "Logistics" },
  { symbol: "CROMPTON", name: "CROMPT GREA CON ELEC LTD", sector: "Capital Goods" },
  { symbol: "CUMMINSIND", name: "CUMMINS INDIA LTD", sector: "Capital Goods" },
  { symbol: "DABUR", name: "DABUR INDIA LTD", sector: "FMCG" },
  { symbol: "DALBHARAT", name: "DALMIA BHARAT LIMITED", sector: "Cement" },
  { symbol: "DELHIVERY", name: "DELHIVERY LIMITED", sector: "Logistics" },
  { symbol: "DIVISLAB", name: "DIVI S LABORATORIES LTD", sector: "Pharma" },
  { symbol: "DIXON", name: "DIXON TECHNO (INDIA) LTD", sector: "Consumer" },
  { symbol: "DLF", name: "DLF LIMITED", sector: "Realty" },
  { symbol: "DMART", name: "AVENUE SUPERMARTS LIMITED", sector: "Retail" },
  { symbol: "DRREDDY", name: "DR. REDDY S LABORATORIES", sector: "Pharma" },
  { symbol: "EICHERMOT", name: "EICHER MOTORS LTD", sector: "Auto" },
  { symbol: "ETERNAL", name: "ETERNAL LIMITED", sector: "Consumer" },
  { symbol: "FEDERALBNK", name: "FEDERAL BANK LTD", sector: "Banking" },
  { symbol: "FORCEMOT", name: "FORCE MOTORS LIMITED", sector: "Auto" },
  { symbol: "FORTIS", name: "FORTIS HEALTHCARE LTD", sector: "Healthcare" },
  { symbol: "GAIL", name: "GAIL (INDIA) LTD", sector: "Energy" },
  { symbol: "GLENMARK", name: "GLENMARK PHARMACEUTICALS", sector: "Pharma" },
  { symbol: "GMRAIRPORT", name: "GMR AIRPORTS LIMITED", sector: "Infrastructure" },
  { symbol: "GODFRYPHLP", name: "GODFREY PHILLIPS INDIA LT", sector: "Consumer" },
  { symbol: "GODREJCP", name: "GODREJ CONSUMER PRODUCTS", sector: "FMCG" },
  { symbol: "GODREJPROP", name: "GODREJ PROPERTIES LTD", sector: "Realty" },
  { symbol: "GRASIM", name: "GRASIM INDUSTRIES LTD", sector: "Cement" },
  { symbol: "GVT&D", name: "GE VERNOVA T&D INDIA LTD", sector: "Capital Goods" },
  { symbol: "HAL", name: "HINDUSTAN AERONAUTICS LTD", sector: "Defence" },
  { symbol: "HAVELLS", name: "HAVELLS INDIA LIMITED", sector: "Consumer" },
  { symbol: "HCLTECH", name: "HCL TECHNOLOGIES LTD", sector: "IT" },
  { symbol: "HDFCAMC", name: "HDFC AMC LIMITED", sector: "Finance" },
  { symbol: "HDFCBANK", name: "HDFC BANK LTD", sector: "Banking" },
  { symbol: "HDFCLIFE", name: "HDFC LIFE INS CO LTD", sector: "Insurance" },
  { symbol: "HEROMOTOCO", name: "HERO MOTOCORP LIMITED", sector: "Auto" },
  { symbol: "HINDALCO", name: "HINDALCO  INDUSTRIES  LTD", sector: "Metal" },
  { symbol: "HINDPETRO", name: "HINDUSTAN PETROLEUM CORP", sector: "Energy" },
  { symbol: "HINDUNILVR", name: "HINDUSTAN UNILEVER LTD.", sector: "FMCG" },
  { symbol: "HINDZINC", name: "HINDUSTAN ZINC LIMITED", sector: "Metal" },
  { symbol: "HYUNDAI", name: "HYUNDAI MOTOR INDIA LTD", sector: "Auto" },
  { symbol: "ICICIBANK", name: "ICICI BANK LTD.", sector: "Banking" },
  { symbol: "ICICIGI", name: "ICICI LOMBARD GIC LIMITED", sector: "Insurance" },
  { symbol: "ICICIPRULI", name: "ICICI PRU LIFE INS CO LTD", sector: "Insurance" },
  { symbol: "IDEA", name: "VODAFONE IDEA LIMITED", sector: "Telecom" },
  { symbol: "IDFCFIRSTB", name: "IDFC FIRST BANK LIMITED", sector: "Banking" },
  { symbol: "IEX", name: "INDIAN ENERGY EXC LTD", sector: "Finance" },
  { symbol: "INDHOTEL", name: "THE INDIAN HOTELS CO. LTD", sector: "Consumer" },
  { symbol: "INDIANB", name: "INDIAN BANK", sector: "Banking" },
  { symbol: "INDIGO", name: "INTERGLOBE AVIATION LTD", sector: "Aviation" },
  { symbol: "INDUSINDBK", name: "INDUSIND BANK LIMITED", sector: "Banking" },
  { symbol: "INDUSTOWER", name: "INDUS TOWERS LIMITED", sector: "Telecom" },
  { symbol: "INFY", name: "INFOSYS LIMITED", sector: "IT" },
  { symbol: "INOXWIND", name: "INOX WIND LIMITED", sector: "Power" },
  { symbol: "IOC", name: "INDIAN OIL CORP LTD", sector: "Energy" },
  { symbol: "IREDA", name: "INDIAN RENEWABLE ENERGY", sector: "Finance" },
  { symbol: "IRFC", name: "INDIAN RAILWAY FIN CORP L", sector: "Finance" },
  { symbol: "ITC", name: "ITC LTD", sector: "FMCG" },
  { symbol: "JINDALSTEL", name: "JINDAL STEEL LIMITED", sector: "Metal" },
  { symbol: "JIOFIN", name: "JIO FIN SERVICES LTD", sector: "Finance" },
  { symbol: "JSWENERGY", name: "JSW ENERGY LIMITED", sector: "Power" },
  { symbol: "JSWSTEEL", name: "JSW STEEL LIMITED", sector: "Metal" },
  { symbol: "JUBLFOOD", name: "JUBILANT FOODWORKS LTD", sector: "Consumer" },
  { symbol: "KALYANKJIL", name: "KALYAN JEWELLERS IND LTD", sector: "Consumer" },
  { symbol: "KAYNES", name: "KAYNES TECHNOLOGY IND LTD", sector: "IT" },
  { symbol: "KEI", name: "KEI INDUSTRIES LTD.", sector: "Capital Goods" },
  { symbol: "KFINTECH", name: "KFIN TECHNOLOGIES LIMITED", sector: "Finance" },
  { symbol: "KOTAKBANK", name: "KOTAK MAHINDRA BANK LTD", sector: "Banking" },
  { symbol: "KPITTECH", name: "KPIT TECHNOLOGIES LIMITED", sector: "IT" },
  { symbol: "LAURUSLABS", name: "LAURUS LABS LIMITED", sector: "Pharma" },
  { symbol: "LICHSGFIN", name: "LIC HOUSING FINANCE LTD", sector: "NBFC" },
  { symbol: "LICI", name: "LIFE INSURA CORP OF INDIA", sector: "Insurance" },
  { symbol: "LODHA", name: "LODHA DEVELOPERS LIMITED", sector: "Realty" },
  { symbol: "LT", name: "LARSEN & TOUBRO LTD.", sector: "Infrastructure" },
  { symbol: "LTF", name: "L&T FINANCE LIMITED", sector: "Finance" },
  { symbol: "LTIM", name: "LTIMindtree Limited", sector: "IT" },
  { symbol: "LUPIN", name: "LUPIN LIMITED", sector: "Pharma" },
  { symbol: "M&M", name: "MAHINDRA & MAHINDRA LTD", sector: "Auto" },
  { symbol: "MANAPPURAM", name: "MANAPPURAM FINANCE LTD", sector: "NBFC" },
  { symbol: "MANKIND", name: "MANKIND PHARMA LIMITED", sector: "Pharma" },
  { symbol: "MARICO", name: "MARICO LIMITED", sector: "FMCG" },
  { symbol: "MARUTI", name: "MARUTI SUZUKI INDIA LTD.", sector: "Auto" },
  { symbol: "MAXHEALTH", name: "MAX HEALTHCARE INS LTD", sector: "Healthcare" },
  { symbol: "MAZDOCK", name: "MAZAGON DOCK SHIPBUIL LTD", sector: "Defence" },
  { symbol: "MCX", name: "MULTI COMMODITY EXCHANGE", sector: "Finance" },
  { symbol: "MFSL", name: "MAX FINANCIAL SERV LTD", sector: "Insurance" },
  { symbol: "MOTHERSON", name: "SAMVRDHNA MTHRSN INTL LTD", sector: "Auto" },
  { symbol: "MOTILALOFS", name: "MOTILAL OSWAL FIN LTD", sector: "Finance" },
  { symbol: "MPHASIS", name: "MPHASIS LIMITED", sector: "IT" },
  { symbol: "MUTHOOTFIN", name: "MUTHOOT FINANCE LIMITED", sector: "NBFC" },
  { symbol: "NAM-INDIA", name: "NIPPON L I A M LTD", sector: "Finance" },
  { symbol: "NATIONALUM", name: "NATIONAL ALUMINIUM CO LTD", sector: "Metal" },
  { symbol: "NAUKRI", name: "INFO EDGE (I) LTD", sector: "IT" },
  { symbol: "NBCC", name: "NBCC (INDIA) LIMITED", sector: "Infrastructure" },
  { symbol: "NESTLEIND", name: "NESTLE INDIA LIMITED", sector: "FMCG" },
  { symbol: "NHPC", name: "NHPC LTD", sector: "Power" },
  { symbol: "NMDC", name: "NMDC LTD.", sector: "Mining" },
  { symbol: "NTPC", name: "NTPC LTD", sector: "Power" },
  { symbol: "NYKAA", name: "FSN E COMMERCE VENTURES", sector: "Retail" },
  { symbol: "OBEROIRLTY", name: "OBEROI REALTY LIMITED", sector: "Realty" },
  { symbol: "OFSS", name: "ORACLE FIN SERV SOFT LTD.", sector: "IT" },
  { symbol: "OIL", name: "OIL INDIA LTD", sector: "Energy" },
  { symbol: "ONGC", name: "OIL AND NATURAL GAS CORP.", sector: "Energy" },
  { symbol: "PAGEIND", name: "PAGE INDUSTRIES LTD", sector: "Consumer" },
  { symbol: "PATANJALI", name: "PATANJALI FOODS LIMITED", sector: "Consumer" },
  { symbol: "PAYTM", name: "ONE 97 COMMUNICATIONS LTD", sector: "Finance" },
  { symbol: "PERSISTENT", name: "PERSISTENT SYSTEMS LTD", sector: "IT" },
  { symbol: "PETRONET", name: "PETRONET LNG LIMITED", sector: "Energy" },
  { symbol: "PFC", name: "POWER FIN CORP LTD.", sector: "Finance" },
  { symbol: "PGEL", name: "PG ELECTROPLAST LTD", sector: "Capital Goods" },
  { symbol: "PHOENIXLTD", name: "THE PHOENIX MILLS LTD", sector: "Retail" },
  { symbol: "PIDILITIND", name: "PIDILITE INDUSTRIES LTD", sector: "Chemical" },
  { symbol: "PIIND", name: "PI INDUSTRIES LTD", sector: "Chemical" },
  { symbol: "PNBHOUSING", name: "PNB HOUSING FIN LTD.", sector: "NBFC" },
  { symbol: "PNB", name: "PUNJAB NATIONAL BANK", sector: "Banking" },
  { symbol: "POLICYBZR", name: "PB FINTECH LIMITED", sector: "Finance" },
  { symbol: "POLYCAB", name: "POLYCAB INDIA LIMITED", sector: "Capital Goods" },
  { symbol: "POWERGRID", name: "POWER GRID CORP. LTD.", sector: "Power" },
  { symbol: "POWERINDIA", name: "HITACHI ENERGY INDIA LTD", sector: "Capital Goods" },
  { symbol: "PREMIERENE", name: "PREMIER ENERGIES LIMITED", sector: "Energy" },
  { symbol: "PRESTIGE", name: "PRESTIGE ESTATE LTD", sector: "Realty" },
  { symbol: "RADICO", name: "RADICO KHAITAN LTD", sector: "Consumer" },
  { symbol: "RBLBANK", name: "RBL BANK LIMITED", sector: "Banking" },
  { symbol: "RECLTD", name: "REC LIMITED", sector: "Finance" },
  { symbol: "RELIANCE", name: "RELIANCE INDUSTRIES LTD", sector: "Energy" },
  { symbol: "RVNL", name: "RAIL VIKAS NIGAM LIMITED", sector: "Infrastructure" },
  { symbol: "SAIL", name: "STEEL AUTHORITY OF INDIA", sector: "Metal" },
  { symbol: "SBICARD", name: "SBI CARDS & PAY SER LTD", sector: "Finance" },
  { symbol: "SBILIFE", name: "SBI LIFE INSURANCE CO LTD", sector: "Insurance" },
  { symbol: "SBIN", name: "STATE BANK OF INDIA", sector: "Banking" },
  { symbol: "SHREECEM", name: "SHREE CEMENT LIMITED", sector: "Cement" },
  { symbol: "SHRIRAMFIN", name: "SHRIRAM FINANCE LIMITED", sector: "NBFC" },
  { symbol: "SIEMENS", name: "SIEMENS LTD", sector: "Capital Goods" },
  { symbol: "SOLARINDS", name: "SOLAR INDUSTRIES (I) LTD", sector: "Capital Goods" },
  { symbol: "SONACOMS", name: "SONA BLW PRECISION FRGS L", sector: "Auto" },
  { symbol: "SRF", name: "SRF LTD", sector: "Chemical" },
  { symbol: "SUNPHARMA", name: "SUN PHARMACEUTICAL IND L", sector: "Pharma" },
  { symbol: "SUPREMEIND", name: "SUPREME INDUSTRIES LTD", sector: "Capital Goods" },
  { symbol: "SUZLON", name: "SUZLON ENERGY LIMITED", sector: "Power" },
  { symbol: "SWIGGY", name: "SWIGGY LIMITED", sector: "Consumer" },
  { symbol: "TATACONSUM", name: "TATA CONSUMER PRODUCT LTD", sector: "FMCG" },
  { symbol: "TATAELXSI", name: "TATA ELXSI LIMITED", sector: "IT" },
  { symbol: "TATAPOWER", name: "TATA POWER CO LTD", sector: "Power" },
  { symbol: "TATASTEEL", name: "TATA STEEL LIMITED", sector: "Metal" },
  { symbol: "TCS", name: "TATA CONSULTANCY SERV LT", sector: "IT" },
  { symbol: "TECHM", name: "TECH MAHINDRA LIMITED", sector: "IT" },
  { symbol: "TIINDIA", name: "TUBE INVEST OF INDIA LTD", sector: "Capital Goods" },
  { symbol: "TITAN", name: "TITAN COMPANY LIMITED", sector: "Consumer" },
  { symbol: "TMPV", name: "TATA MOTORS PASS VEH LTD", sector: "Auto" },
  { symbol: "TORNTPHARM", name: "TORRENT PHARMACEUTICALS L", sector: "Pharma" },
  { symbol: "TRENT", name: "TRENT LTD", sector: "Retail" },
  { symbol: "TVSMOTOR", name: "TVS MOTOR COMPANY  LTD", sector: "Auto" },
  { symbol: "ULTRACEMCO", name: "ULTRATECH CEMENT LIMITED", sector: "Cement" },
  { symbol: "UNIONBANK", name: "UNION BANK OF INDIA", sector: "Banking" },
  { symbol: "UNITDSPR", name: "UNITED SPIRITS LIMITED", sector: "FMCG" },
  { symbol: "UNOMINDA", name: "UNO MINDA LIMITED", sector: "Auto" },
  { symbol: "UPL", name: "UPL LIMITED", sector: "Chemical" },
  { symbol: "VBL", name: "VARUN BEVERAGES LIMITED", sector: "FMCG" },
  { symbol: "VEDL", name: "VEDANTA LIMITED", sector: "Metal" },
  { symbol: "VMM", name: "VISHAL MEGA MART LIMITED", sector: "Retail" },
  { symbol: "VOLTAS", name: "VOLTAS LTD", sector: "Capital Goods" },
  { symbol: "WAAREEENER", name: "WAAREE ENERGIES LIMITED", sector: "Energy" },
  { symbol: "WIPRO", name: "WIPRO LTD", sector: "IT" },
  { symbol: "YESBANK", name: "YES BANK LIMITED", sector: "Banking" },
  { symbol: "ZYDUSLIFE", name: "ZYDUS LIFESCIENCES LTD", sector: "Pharma" },
];
